package com.banking.report.service;

import com.banking.report.dto.GenerateReportRequest;
import com.banking.report.dto.ReportResponse;
import com.banking.report.module.entity.Report;
import com.banking.report.repository.ReportRepository;
import com.banking.core.auth.repository.UserRepository;
import com.banking.core.auth.module.entity.User;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Report Service
 *
 * Service layer for Report generation and management.
 *
 * @author Banking System
 */
@Service
@RequiredArgsConstructor
public class ReportService {

    private static final Logger logger = LoggerFactory.getLogger(ReportService.class);

    private final ReportRepository reportRepository;
    private final UserRepository userRepository;
    private final ObjectMapper objectMapper;

    private static final String REPORTS_DIR = "reports";

    /**
     * Generate a new report
     */
    @Transactional
    public ReportResponse generateReport(GenerateReportRequest request, Long generatedByUserId) {
        logger.info("Generating {} report from {} to {} for user {}",
                   request.getReportType(), request.getStartDate(), request.getEndDate(), generatedByUserId);

        // Get the user
        User generatedBy = userRepository.findById(generatedByUserId)
                .orElseThrow(() -> new IllegalArgumentException("User not found: " + generatedByUserId));

        // Create report entity
        Report report = new Report();
        report.setReportType(request.getReportType());
        report.setGeneratedBy(generatedBy);
        report.setStartDate(request.getStartDate());
        report.setEndDate(request.getEndDate());
        report.setFormat(request.getFormat());

        // Serialize parameters to JSON
        if (request.getParameters() != null && !request.getParameters().isEmpty()) {
            try {
                report.setParameters(objectMapper.writeValueAsString(request.getParameters()));
            } catch (JsonProcessingException e) {
                logger.warn("Failed to serialize report parameters: {}", e.getMessage());
            }
        }

        // Generate the actual report file
        String filePath = generateReportFile(report);
        report.setFilePath(filePath);

        Report savedReport = reportRepository.save(report);
        logger.info("Generated report with ID: {}", savedReport.getId());

        return mapToReportResponse(savedReport);
    }

    /**
     * Get all reports
     */
    public List<ReportResponse> getAllReports() {
        logger.info("Retrieving all reports");
        return reportRepository.findAll().stream()
                .map(this::mapToReportResponse)
                .collect(Collectors.toList());
    }

    /**
     * Get report by ID
     */
    public ReportResponse getReportById(Long id) {
        logger.info("Retrieving report with ID: {}", id);
        Report report = reportRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Report not found with ID: " + id));
        return mapToReportResponse(report);
    }

    /**
     * Get reports by type
     */
    public List<ReportResponse> getReportsByType(com.banking.core.enums.ReportType reportType) {
        logger.info("Retrieving reports of type: {}", reportType);
        return reportRepository.findByReportType(reportType).stream()
                .map(this::mapToReportResponse)
                .collect(Collectors.toList());
    }

    /**
     * Get reports generated by user
     */
    public List<ReportResponse> getReportsByUser(Long userId) {
        logger.info("Retrieving reports generated by user: {}", userId);
        return reportRepository.findByGeneratedById(userId).stream()
                .map(this::mapToReportResponse)
                .collect(Collectors.toList());
    }

    /**
     * Get reports in date range
     */
    public List<ReportResponse> getReportsInDateRange(LocalDateTime startDate, LocalDateTime endDate) {
        logger.info("Retrieving reports from {} to {}", startDate, endDate);
        return reportRepository.findByGeneratedDateBetween(startDate, endDate).stream()
                .map(this::mapToReportResponse)
                .collect(Collectors.toList());
    }

    /**
     * Delete report
     */
    @Transactional
    public void deleteReport(Long id) {
        logger.info("Deleting report with ID: {}", id);

        Report report = reportRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Report not found with ID: " + id));

        // Delete the file if it exists
        if (report.getFilePath() != null) {
            try {
                Files.deleteIfExists(Paths.get(report.getFilePath()));
            } catch (IOException e) {
                logger.warn("Failed to delete report file: {}", report.getFilePath(), e);
            }
        }

        reportRepository.delete(report);
        logger.info("Deleted report with ID: {}", id);
    }

    /**
     * Generate the actual report file
     */
    private String generateReportFile(Report report) {
        try {
            // Create reports directory if it doesn't exist
            Path reportsDir = Paths.get(REPORTS_DIR);
            Files.createDirectories(reportsDir);

            // Generate filename
            String fileName = String.format("%s_%d_%s.%s",
                report.getReportType().toString().toLowerCase(),
                report.getId(),
                report.getGeneratedDate().toString().replace(":", "-"),
                report.getFormat().toString().toLowerCase()
            );

            Path filePath = reportsDir.resolve(fileName);

            // Generate report content based on type
            String content = generateReportContent(report);
            Files.write(filePath, content.getBytes());

            logger.info("Generated report file: {}", filePath.toString());
            return filePath.toString();

        } catch (IOException e) {
            logger.error("Failed to generate report file", e);
            throw new RuntimeException("Failed to generate report file", e);
        }
    }

    /**
     * Generate report content based on type
     */
    private String generateReportContent(Report report) {
        StringBuilder content = new StringBuilder();

        // Header
        content.append("BANKING SYSTEM REPORT\n");
        content.append("====================\n\n");

        content.append("Report Type: ").append(report.getReportType()).append("\n");
        content.append("Generated By: ").append(report.getGeneratedBy().getUsername()).append("\n");
        content.append("Generated Date: ").append(report.getGeneratedDate()).append("\n");
        content.append("Period: ").append(report.getStartDate()).append(" to ").append(report.getEndDate()).append("\n\n");

        // Generate content based on report type
        switch (report.getFormat()) {
            case CSV:
                content.append(generateCSVContent(report));
                break;
            case JSON:
                content.append(generateJSONContent(report));
                break;
            case PDF:
            case XML:
            default:
                content.append(generateTextContent(report));
                break;
        }

        content.append("\n\nReport generated by Banking System v1.0");
        return content.toString();
    }

    private String generateCSVContent(Report report) {
        // Simple CSV format
        return "Date,Description,Amount,Status\n" +
               "2024-01-01,Sample Transaction,100.00,COMPLETED\n" +
               "2024-01-02,Another Transaction,250.50,PENDING\n";
    }

    private String generateJSONContent(Report report) {
        // Simple JSON format
        return "{\n" +
               "  \"report\": {\n" +
               "    \"type\": \"" + report.getReportType() + "\",\n" +
               "    \"period\": {\n" +
               "      \"start\": \"" + report.getStartDate() + "\",\n" +
               "      \"end\": \"" + report.getEndDate() + "\"\n" +
               "    },\n" +
               "    \"summary\": {\n" +
               "      \"totalTransactions\": 150,\n" +
               "      \"totalAmount\": 25000.00\n" +
               "    }\n" +
               "  }\n" +
               "}\n";
    }

    private String generateTextContent(Report report) {
        return "SUMMARY:\n" +
               "- Total Transactions: 150\n" +
               "- Total Amount: $25,000.00\n" +
               "- Average Transaction: $166.67\n" +
               "- Success Rate: 98.5%\n";
    }

    private ReportResponse mapToReportResponse(Report report) {
        // Check if file exists and get size
        Long fileSize = null;
        String downloadUrl = null;
        if (report.getFilePath() != null) {
            try {
                Path path = Paths.get(report.getFilePath());
                if (Files.exists(path)) {
                    fileSize = Files.size(path);
                    downloadUrl = "/api/reports/download/" + report.getId();
                }
            } catch (IOException e) {
                logger.warn("Failed to get file info for report {}: {}", report.getId(), e.getMessage());
            }
        }

        return ReportResponse.builder()
                .id(report.getId())
                .reportType(report.getReportType())
                .generatedById(report.getGeneratedBy().getId())
                .generatedByUsername(report.getGeneratedBy().getUsername())
                .generatedDate(report.getGeneratedDate())
                .startDate(report.getStartDate())
                .endDate(report.getEndDate())
                .filePath(report.getFilePath())
                .format(report.getFormat())
                .parameters(report.getParameters())
                .downloadUrl(downloadUrl)
                .fileSize(fileSize)
                .build();
    }
}
