package com.banking.report.controller;

import com.banking.core.enums.ReportFormat;
import com.banking.core.enums.ReportType;
import com.banking.report.dto.GenerateReportRequest;
import com.banking.report.dto.ReportResponse;
import com.banking.report.service.ReportService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.*;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Report Controller
 *
 * REST API for Report generation and management.
 * Supports generating, retrieving, and downloading reports.
 *
 * @author Banking System
 */
@RestController
@RequestMapping("/api/reports")
@RequiredArgsConstructor
public class ReportController {

    private static final Logger logger = LoggerFactory.getLogger(ReportController.class);

    private final ReportService reportService;

    /**
     * Generate a new report
     */
    @PostMapping("/generate")
    @PreAuthorize("hasAnyRole('MANAGER', 'ADMIN')")
    public ResponseEntity<ReportResponse> generateReport(@Valid @RequestBody GenerateReportRequest request) {
        logger.info("Received request to generate {} report", request.getReportType());

        // Get current user ID
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        // In a real implementation, you'd extract the user ID from the authentication token
        Long userId = 1L; // Placeholder - should be extracted from JWT token

        ReportResponse response = reportService.generateReport(request, userId);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    /**
     * Get all reports
     */
    @GetMapping
    @PreAuthorize("hasAnyRole('MANAGER', 'ADMIN')")
    public ResponseEntity<List<ReportResponse>> getAllReports() {
        return ResponseEntity.ok(reportService.getAllReports());
    }

    /**
     * Get report by ID
     */
    @GetMapping("/{id}")
    @PreAuthorize("hasAnyRole('MANAGER', 'ADMIN')")
    public ResponseEntity<ReportResponse> getReportById(@PathVariable Long id) {
        return ResponseEntity.ok(reportService.getReportById(id));
    }

    /**
     * Get reports by type
     */
    @GetMapping("/type/{reportType}")
    @PreAuthorize("hasAnyRole('MANAGER', 'ADMIN')")
    public ResponseEntity<List<ReportResponse>> getReportsByType(@PathVariable ReportType reportType) {
        return ResponseEntity.ok(reportService.getReportsByType(reportType));
    }

    /**
     * Get reports generated by current user
     */
    @GetMapping("/my-reports")
    @PreAuthorize("hasAnyRole('MANAGER', 'ADMIN')")
    public ResponseEntity<List<ReportResponse>> getMyReports() {
        // In a real implementation, extract user ID from JWT token
        Long userId = 1L; // Placeholder
        return ResponseEntity.ok(reportService.getReportsByUser(userId));
    }

    /**
     * Get reports in date range
     */
    @GetMapping("/date-range")
    @PreAuthorize("hasAnyRole('MANAGER', 'ADMIN')")
    public ResponseEntity<List<ReportResponse>> getReportsInDateRange(
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime startDate,
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime endDate) {
        return ResponseEntity.ok(reportService.getReportsInDateRange(startDate, endDate));
    }

    /**
     * Download report file
     */
    @GetMapping("/download/{id}")
    @PreAuthorize("hasAnyRole('MANAGER', 'ADMIN')")
    public ResponseEntity<byte[]> downloadReport(@PathVariable Long id) {
        try {
            ReportResponse report = reportService.getReportById(id);

            if (report.getFilePath() == null) {
                return ResponseEntity.notFound().build();
            }

            Path filePath = Paths.get(report.getFilePath());
            if (!Files.exists(filePath)) {
                return ResponseEntity.notFound().build();
            }

            byte[] content = Files.readAllBytes(filePath);

            HttpHeaders headers = new HttpHeaders();
            String filename = String.format("%s_report_%d.%s",
                report.getReportType().toString().toLowerCase(),
                report.getId(),
                report.getFormat().toString().toLowerCase());

            headers.setContentDispositionFormData("attachment", filename);

            // Set content type based on format
            MediaType mediaType = switch (report.getFormat()) {
                case PDF -> MediaType.APPLICATION_PDF;
                case EXCEL -> new MediaType("application", "vnd.ms-excel");
                case CSV -> new MediaType("text", "csv");
                case XML -> MediaType.APPLICATION_XML;
                case JSON -> MediaType.APPLICATION_JSON;
            };

            return ResponseEntity.ok()
                    .headers(headers)
                    .contentType(mediaType)
                    .body(content);

        } catch (Exception e) {
            logger.error("Error downloading report {}: {}", id, e.getMessage());
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Delete report
     */
    @DeleteMapping("/{id}")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<Void> deleteReport(@PathVariable Long id) {
        reportService.deleteReport(id);
        return ResponseEntity.noContent().build();
    }

    /**
     * Get available report types
     */
    @GetMapping("/types")
    @PreAuthorize("hasAnyRole('MANAGER', 'ADMIN')")
    public ResponseEntity<List<String>> getAvailableReportTypes() {
        return ResponseEntity.ok(List.of(
            "DAILY_TRANSACTIONS",
            "ACCOUNT_SUMMARY",
            "CUSTOMER_ACTIVITY",
            "AUDIT_LOG",
            "FINANCIAL_SUMMARY"
        ));
    }

    /**
     * Get available report formats
     */
    @GetMapping("/formats")
    @PreAuthorize("hasAnyRole('MANAGER', 'ADMIN')")
    public ResponseEntity<List<String>> getAvailableReportFormats() {
        return ResponseEntity.ok(List.of(
            "PDF",
            "CSV",
            "JSON",
            "XML"
        ));
    }
}
